### PR TITLE
Ensure SDS config and server config agree

### PR DESCRIPTION
**Pull request by charvolant**
Also bump development version
Also integration test to ensure server picks up config correctly

### CODE REVIEW

**Comment by charvolant** [comment]
Intended to fix problems in #20

**Review by vjrj — APPROVED** [review]
Review and tested. It fix #20 . Thanks indeed @charvolant

**Comment by vjrj** [comment]
@charvolant any problem to merge this?

**Comment by vjrj** [comment]
Hi @charvolant: Any problem to merge this? I tested/reviewed already. Can I help anyhow?

**Comment by charvolant** [comment]
This appears to have made it into the maintenance-1.1 branch, which is what is being used in production ATM.
To be replaced with a merge from maintenance-1.1 into develop.

**Pull request closed without merging**
